spring:
  application:
    name: Hotel-Service

  config:
    import: optional:configserver:http://localhost:8085

  datasource:
    url: jdbc:mysql://localhost:3306/HotelMicroservice?useSSL=false&serverTimezone=UTC
    username: root
    password: Shubham@1997
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

server:
  port: 8082

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE

#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka
